FROM node:10-alpine

RUN mkdir -p never_forget/app
WORKDIR /never_forget/app

COPY package.json /never_forget/app
COPY package-lock.json /never_forget/app

RUN npm install

COPY . /never_forget/app

CMD ["npm", "run", "start"]