FROM node:10-alpine

RUN mkdir -p never_forget/server
WORKDIR /never_forget/server

COPY package.json /never_forget/server
COPY package-lock.json /never_forget/server

RUN npm install

COPY . /never_forget/server

CMD ["npm", "run", "dev"]